### ISSUE TITLE
Cannot modify text 

### ISSUE THREAD

**Issue by ryedunn** [kamek-pf/ntfd#14]
I have both icon fonts (weather and material) installed and referenced in my config.
font-8 = WeatherIcons:style=Regular:size=16;3
font-9 = MaterialIcons:style=Regular:size=12;3

[module/weather]
type = custom/script
exec = busctl --user -j get-property io.ntfd /weather openweathermap.strings RenderedTemplate | jq -r .data
interval = 60
label-font = 9

Data is in my polybar and I can change the icon sizes, but the numbers are too big, how can the numbers be adjusted?

**Comment by kamek-pf** [comment]
That's a Polybar thing, I'm pretty sure the `label-font` property does nothing for `custom/script` (it doesn't even show in [the docs](https://github.com/polybar/polybar/wiki/Module:-script)).

IIRC, for each glyph, Polybar tries each font in order until it finds one that can render the current glyph.
One of the font you previously listed (before MaterialIcons and WeatherIcons) probably matches the numbers so Polybar just uses that and moves on.

I don't think there's a good solution for it currently, you have to list font in a way that works with everything :/
... Although with 10 you're not gonna have a fun time :s
