### ISSUE TITLE
Weather icon problem

### ISSUE THREAD

**Issue by Cyberdr3am** [kamek-pf/ntfd#19]
Hi,
Thx for this program.

When i use the AUR version i have got the the same error

https://github.com/kamek-pf/ntfd/issues/17

After using you last release all work great but not the weather icon.

`busctl --user -j get-property io.ntfd /weather openweathermap.strings RenderedTemplate | jq -r .data`

 26°C   26°C

Polybar config font

font-0 = "Inconsolata Nerd Font:bold:size=11;2"
font-1 = "WeatherIcons:size=17"
font-2 = "UbuntuMono Nerd Font:size=14;3"
font-3 = "Font Awesome 5 Free:style=Regular:pixelsize=8;1"
font-4 = "Font Awesome 5 Free:style=Solid:pixelsize=8;1"
font-5 = "Font Awesome 5 Brands:pixelsize=8;1"

If i use weather icon on the first place all other symbol are weather icon but not the weather module.

Thx

**Comment by kamek-pf** [comment]
That would be a Polybar config issue.

If you run the `busctl` command in a terminal and see some output, the tool is doing its job, it has no notion of rendering at all and isn't aware of Polybar.

You need to order your fonts in a way that works, or use the `label-font` property in your config.
I'm guessing the nerd font is messing things up, try adding `label-font = 2` (it's one-indexed, unlike the `font-X` property).

**Comment by Cyberdr3am** [comment]
Thx for the help.
I try to change the font order but i never see weather icon.
If i use label-font = 2 nothing change
