### ISSUE TITLE
Weird rendering with polybar integration of weather

### ISSUE THREAD

**Issue by Zelo28** [kamek-pf/ntfd#2]
Hi, i am making my own polybar with your deamon, it wont display the current temperature and the forecast temperature.
All the font are set correctly and the module is a copy paste of your example. Can u find a solution for this?
(Ps. i am non that experienced with arch linux)

![immagine](https://user-images.githubusercontent.com/44406491/86522523-83c33380-be5f-11ea-9b11-574819520eee.png)

**Comment by kamek-pf** [comment]
With your current config, removing the `label-font` property form the weather module should do the trick.

Polybar tries to render your module using the font specified by label-font (or the very first font if that property is missing). 
If it fails to render a character, it tries the next font in the list, until one of them matches.

In your case, Weather Icons is the last font in the list, and it doesn't include numbers, so the rendering fails and stops there.

**Comment by Zelo28** [comment]
Removing `label-font` does not work, i had to change `labal-font = Fira Code:pixelsize = 10`
And i had to wait the interval to see the weather module.

**Comment by kamek-pf** [comment]
AFAIK, `label-font` takes an index, not a font config, what you did should effectively be the same as removing the property entirely.
You're right though, you do have to restart the daemon and wait for a sync to see the changes u.u (or restart polybar)
