### ISSUE TITLE
Weather Icons won't show properly when adding the module to Polybar

### ISSUE THREAD

**Issue by eneko98** [kamek-pf/ntfd#22]
I have done everything as it says in the Github but for some reason I don't get the cloud icons, I get some gear icons instead.

if I do: busctl --user -j get-property io.ntfd /weather openweathermap.strings RenderedTemplate | jq -r .data I get:  22°C   22°C

Does anyone know why this is?

**Comment by kamek-pf** [comment]
See my response here : https://github.com/kamek-pf/ntfd/issues/19#issuecomment-1132169329

That's a Polybar config issue, it's not using the font you think it does.
