### ISSUE TITLE
When I run ntfd I receive the error: ntfd: Network.Socket.connect: <socket: 12>: does not exist (Connection refused)

### ISSUE THREAD

**Issue by jblais493** [kamek-pf/ntfd#3]
I am trying to get this to work, I am kinda a noob when it comes to sockets. Could you help me out on this?

**Comment by kamek-pf** [comment]
Hey there,

Let's try to sort this out, first can you share your config.toml file ? this should help pinpoint which module is causing issues.
Hopefully I can improve the error messages, this is a bit cryptic

**Comment by kamek-pf** [comment]
Actually, I think the only way to get this error is to have the `mpd` module enabled while `mpd` isn't actually running.
Could also be that `ntfd` starts before `mpd`.

Can you make sure `mpd` is up and running ? Or disable this module if you're not actually using it :p

**Comment by jblais493** [comment]
Hey thanks for the quick response! That seemed to be the exact issue, my mpd was already running and this called it a second time, throwing the error. 

Thank you! :)

**Comment by kamek-pf** [comment]
Note that this doesn't launch mpd, it just tries to connect to an existing instance, so make sure it's running beforehand ;o
