### ISSUE TITLE
Weather 'trend' icon does not display

### ISSUE THREAD

**Issue by silentjay** [kamek-pf/ntfd#4]
The trend icon in the weather module does not display. I looked in "weather icons" and can not find the trend icons. I assume they are in a different font package? If so can you tell me which so I can make sure it is installed?

**Comment by kamek-pf** [comment]
Hey there,
The package I used is in the AUR: `aur/ttf-weather-icons`

**Comment by silentjay** [comment]
Hi thanks for the reply. That package the one I believe i'm using using (https://erikflowers.github.io/weather-icons/):
`fc-list | grep -i weather`
`/home/me/.fonts/weathericons-regular-webfont.ttf: Weather Icons:style=Regular`
`/home/me/.fonts/weathericons-regular-webfont.woff: Weather Icons:style=Regular`

The weather icons, clouds/sun/rain etc display fine, but the trend icons are missing. A look on https://erikflowers.github.io/weather-icons/ and loading the ttf file into https://mathew-kurian.github.io/CharacterMap/ suggests that the trend glyph your using isn't part of this font package.

![image](https://user-images.githubusercontent.com/3902481/99947548-0e092700-2d70-11eb-8eb4-c27894c6bc87.png)

**Comment by kamek-pf** [comment]
Oh, I see what you mean. This part actually depends on both Weather Icons and Material Icons.
I realize just now that this isn't even specified in the readme, I guess I forgot about this part when I ported `polybar-forecast`, sorry,

I'll update the readme right now, thank you for reporting this !

**Comment by silentjay** [comment]
Glad I could help, it's a great module and thanks for sharing it with the community!
