### ISSUE TITLE
Weather icons don't display for some reason

### ISSUE THREAD

**Issue by Adelaide-b** [kamek-pf/ntfd#6]
Okay so for some reason the weather icons don't display properly in my polybar. Instead of the clouds I get two cogs.. and the trend icon is just a regular arrow like this: → and I would like to get them to display properly. Do you have any idea what the issue might be? I checked my polybar config and it doesn't seem like you can set the fonts for the weather icons, it happens automatically in some script I assume, so I don't know why it isn't displaying.

**Comment by Prash-bit** [comment]
Hmm strange, I didn't change anything but now the trend icon does appear, I guess the straight forward arrow only appears when the two temperatures are the same then. Still, I have no idea why the weather icons aren't working and it instead displays to cogs.

**Comment by kamek-pf** [comment]
Hey !
The trend icon will indeed be a straight arrow when both temperatures are the same.
About the weather icon thing, assuming you have the correct font installed, thats a Polybar config issue.
Check out this thread : https://github.com/kamek-pf/ntfd/issues/2

(basically, you have to change the order in which your fonts are specified, Polybar tries to render each glyph in that order, so if another fonts succeeds before Weather Icons, then it stops there and you end up with the wrong glyph).

**Comment by Adelaide-b** [comment]
Hi, thank you for your quick reply, I didn't expect to get one so quickly. I did that and now its working. Here's my config file in case anyone is curious on what order works best.

```
[colors]
background = #cc1a1b35
background-alt = #cc1a1b35
foreground = #d9eeee
foreground-alt = #9ea5b6
primary = #f0cc90
secondary = #dd4949
alert = #964151
focus = #886191
light-blue = #76b1cf
transparent = #00000000

[bar/chocolate]
;monitor = ${env:MONITOR:HDMI-1}
width = 100%
height = 23
;offset-x = 1%
;offset-y = 1%
radius = 0.0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = #f00

; border-size = 1
; border-color = ${colors.transparent}

padding-left = 0
padding-right = 0

module-margin-left = 1
module-margin-right = 2

font-0 = mononoki Nerd Font:size=10;0
font-1 = WeatherIcons:size=12;0
font-2 = Symbols Nerd Font:size=12;0
font-3 = MaterialIcons:size=12;0

modules-left = workspaces
modules-center = weather date
modules-right =  pulseaudio bluetooth xkeyboard

tray-position = left
tray-padding = 0
tray-background = #cc1a1b35

;override-redirect = true

cursor-click = pointer
cursor-scroll = ns-resize

[section/modules]
include-file = ~/.config/polybar/modules.ini

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
;compositing-border = over
pseudo-transparency = true

[global/wm]
margin-top = 5
margin-bottom = 5
```

_Putting the Weather icons before the mononoki font causes some problems for my workspace symbols, probably because some of the symbols I used have the same codes as other symbols in the Weather icons font but the codes for the symbols used by the weather icons font aren't used by the mononoki font luckily, I almost thought it wasn't going to work._

**Comment by kamek-pf** [comment]
Glad I could help ! 
I'll close this, feel free to open a new issue you you notice something wrong.
