### ISSUE TITLE
SocketError {socketErrorMessage = "Network.Socket.connect: <socket: 11>: does not exist (No such file or directory)", socketErrorFatal = True, socketErrorAddress = Just (Address "unix:path=/run/user/1000/bus")}

### ISSUE THREAD

**Issue by paulhersch** [kamek-pf/ntfd#8]
I am not entirely sure how this comes to life, only using the weather module with the standard conf and my owm api keys + city code

I am using Void Linux with musl if that helps

**Comment by kamek-pf** [comment]
While I never tested this build with a musl based system, I doubt it would be an issue.

It looks like a DBus issue, is it running ? 
Can you query it with a tool like DFeet or a CLI equivalent ?

**Comment by paulhersch** [comment]
Yes dbus is running as system service (checked with ```ls /var/service```)

yes i just installed DFeet (the package was called d-feet for some reason)
apparently it seems like I don't have a network dbus thing running, just NetworkManager (System Bus category, org.freedesktop.NetworkManager)

**Comment by paulhersch** [comment]
Switched over to Arch now, so the problems with musl aren't there any more, can still boot into it if you want to work on musl support tho.
