### ISSUE TITLE
ntfd not providing .service (manual install Debian)

### ISSUE THREAD

**Issue by Dev380** [kamek-pf/ntfd#9]
I get this error: Failed to get property RenderedTemplate on interface openweathermap.strings: The name io.ntfd was not provided by any .service files

I used the example weather module for polybar in the README.
How would I fix this?

**Comment by kamek-pf** [comment]
It looks like the DBus API isn't running. Are you sure ntfd is running ?
If you run it manually from the console, what's the output ?

**Comment by kamek-pf** [comment]
No further details here, fee free to reopen.
